#version 450

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(binding = 0, r32f) uniform writeonly image2D outImage;
layout(binding = 1) uniform sampler2D inImage;

layout(push_constant) uniform block
{
	uint mipSize;
    float pad0[3];
};

void main()
{
	ivec2 position = min(ivec2(gl_GlobalInvocationID.xy), ivec2(mipSize - 1)); 

	vec2 uv = (0.5 + vec2(position)) / float(mipSize);
	vec4 depth = texture(inImage, uv);

	imageStore(outImage, position, depth);
}